require(quantmod)
require(PerformanceAnalyticcs)
getSymbols("QAI", from = "2010-01-01")
QAI <- QAI$QAI.Adjusted
QAIr <- monthlyReturn(QAI, type = "log")
names(QAIr) <- c("QAI")
getSymbols("VT", from = "2010-01-01")
VT <- VT$VT.Adjusted
VTr <- monthlyReturn(VT, type = "log")
names(VTr) <- c("VT")
chart.Histogram(VTr, colorset = "lightgrey", border.col = "black", main = "Vanguard Total World Stock ETF")
chart.Histogram(QAIr, colorset = "lightgrey", border.col = "black",  main = "IQ Hedge Multi-Strategy Tracker ETF")
SharpeRatio.annualized(VTr)
SharpeRatio.annualized(QAIr)
SortinoRatio(VTr)
SortinoRatio(QAIr)
PainRatio(VTr)
PainRatio(QAIr)
table.Correlation(QAIr, VTr)
table.Distributions(QAIr)
table.Distributions(VTr)
table.DrawdownsRatio(VTr)
table.DrawdownsRatio(QAIr)
Omega(VTr)
Omega(QAIr)
maxDrawdown(VTr)
maxDrawdown(QAIr)
Return.annualized(VTr)
Return.annualized(QAIr)
VaR(VTr)
VaR(QAIr)
charts.PerformanceSummary(QAIr, main = "IQ Hedge Multi-Strategy Tracker ETF Performance", colorset = "red")
charts.PerformanceSummary(VTr, main = "Vanguard Total World Stock ETF Performance", colorset = "red")
perf <- cbind(VTr, QAIr)
chart.CumReturns(perf, main = "Cumulative Returns", legend.loc = "bottomright")
chart.Drawdown(perf, main = "Drawdown", legend.loc = "bottomright")